### ISSUE TITLE
i am big fan of this theme but now its not compatiable with firefox 39

### ISSUE THREAD

**Issue by maqboolkhan** [zeeeeee/firefox-elementary#13]
kindly solve this compatibility issue and make it available for current firefox version please :smile:

**Comment by zeeeeee** [comment]
Hi, I'm sorry to tell you this theme has been discontinued (and actually this Git version is completely outdated).
If you or anyone else wishes to continue to work on this, please check my comments on this post on Google+ elementary page: https://plus.google.com/u/0/111652418194267965300/posts/YTf6TejaX9q
Thank you for understanding!
